name: 'Setup Deployment Branch'
author: David G. Moore, Jr. <david@dgmjr.io>
description: 'Sets up a deployment branch for your files based on templates from the main branch'
inputs: 
  source-branch:
    description: 'Name of the main branch from which to copy the files (optional; defaults to "main")'
    required: false
    default: 'main'
  configuration:
    description: "The name of the configuration you're using"
    required: true
  

outputs:
  webapp-url:
    description: 'URL to work with your webapp'
branding:
  icon: 'git-branch'
  color: 'blue'
runs:
  using: 'node16'
  main: 'lib/main.js'
