name: 'Setup Deploymeny Branch'
author: David G. Moore, Jr.
description: 'Sets up a deployment branch for your files based on templates from the main branch'
inputs: 
  source-branch:
    description: 'Name of the main branch from which to copy the files (optional; defaults to "main")'
    required: false
    default: 'main'
  replacements:
    description: "A set of key-value pairs (in JSON format) in which to replace placeholders in the main branch files"
    default: '{}'

outputs:
  webapp-url:
    description: 'URL to work with your webapp'
branding:
  icon: 'git-branch'
  color: 'blue'
runs:
  using: 'node16'
  main: 'lib/main.js'
